name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run Lighthouse CI
        run: npx lhci autorun
