name: Main
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Archive node_modules
        run: tar -czf node_modules.tar.gz node_modules
      # - name: Add node_modules/.bin to PATH
      #   run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH
      - name: Upload node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules.tar.gz
  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
      - name: Extract node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Run typecheck
        run: npm run typecheck
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
      - name: Extract node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Run lint
        run: npm run lint
  lighthouse:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
      - name: Run Lighthouse CI
        run: npx lhci autorun --rc-file=lighthouserc.cjs
